name: 'Download File And Create Release'
description: 'A tool for download files offline, and create release include file.'
author: 'HalfCoke'
inputs:
  GITHUB_TOKEN:
    required: true
    description: 'use this to create release'
  DOWNLOAD_URL:
    required: true
    description: 'The download url for file which you want to download'
  FILE_NAME:
    required: false
    description: 'The file name you want to rename for download file'

runs:
  using: "composite"
  steps:
    - name: "Download File"
      id: "download"
      shell: bash
      run: |
        mkdir download
        cd download
        echo "WORK_DIR=$(pwd)" >> $GITHUB_ENV
        wget ${{  inputs.DOWNLOAD_URL  }}
        echo "FILE_NAME=$(ls)" >> $GITHUB_ENV
    - name: "Change FIle Name"
      id: "change"
      shell: bash
      run: |
        cd $WORK_DIR
        if [ "x${{ inputs.FILE_NAME }}" != "x" ]; then
          mv "$FILE_NAME" "${{ inputs.FILE_NAME }}"
          FILE_NAME="${{ inputs.FILE_NAME }}"
        fi
        echo "::set-output name=file_name::$FILE_NAME"

    - name: "Create Release"
      id: "release"
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        name: ${{  steps.change.outputs.file_name  }}
        tag_name: ${{  steps.change.outputs.file_name  }}
        files: download/${{  steps.change.outputs.file_name  }}
